In [6]:
%pip install requests

Requirement already satisfied: requests in c:\Users\123\AppData\Local\anaconda3\Lib\site-packages (2.34.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\123\AppData\Local\anaconda3\Lib\site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\123\AppData\Local\anaconda3\Lib\site-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\123\AppData\Local\anaconda3\Lib\site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\123\AppData\Local\anaconda3\Lib\site-packages (from requests) (2026.7.22)
Note: you may need to restart the kernel to use updated packages.

In [10]:
import requests
import pandas as pd

print("Requests:", requests.__version__)
print("Successfully imported!")

Requests: 2.34.2
Successfully imported!

In [ ]:
import pandas as pd
import requests

In [11]:
url = "https://api.themoviedb.org/3/movie/top_rated?api_key=c697cd5701e7923cc1b74e9e45419362"

response = requests.get(url)

print(response.status_code)

200

In [12]:
df=pd.DataFrame(response.json()['results']) [['adult','id','release_date','title','popularity','vote_average']]

In [13]:
df

,adult,id,release_date,title,popularity,vote_average
0,False,1560520,2026-06-23,Batman: Knightfall Part 1: Knightfall,35.4988,9.095
1,False,980431,2026-07-24,Avatar Aang: The Last Airbender,59.0299,9.033
2,False,1007757,2026-05-01,Swapped,39.3270,8.800
3,False,1632181,2026-03-12,Accidental Partners,12.8826,8.800
4,False,1311031,2025-07-18,Demon Slayer: Kimetsu no Yaiba Infinity Castle,45.3120,8.801
5,False,1621552,2026-08-21,Facing El Chapo,31.3963,8.800
6,False,278,1994-09-23,The Shawshank Redemption,61.5979,8.734
7,False,238,1972-03-14,The Godfather,50.8297,8.700
8,False,687163,2026-03-15,Project Hail Mary,105.2510,8.633
9,False,1232449,2024-10-26,Young Hearts,13.8153,8.600
10,False,936075,2026-04-22,Michael,44.6957,8.596
11,False,389,1957-04-10,12 Angry Men,29.6109,8.576
12,False,240,1974-12-20,The Godfather Part II,32.0273,8.600
13,False,424,1993-12-15,Schindler's List,36.2427,8.570
14,False,1630423,2026-05-06,My Dearest Assassin,15.2472,8.560
15,False,1218925,2025-09-19,Chainsaw Man - The Movie: Reze Arc,28.9780,8.547
16,False,155,2008-07-16,The Dark Knight,57.8041,8.539
17,False,129,2001-07-20,Spirited Away,54.1760,8.537
18,False,497,1999-12-10,The Green Mile,33.2750,8.506
19,False,122,2003-12-17,The Lord of the Rings: The Return of the King,46.7927,8.506

In [21]:
df=pd.DataFrame()

In [14]:
df

,adult,id,release_date,title,popularity,vote_average
0,False,1560520,2026-06-23,Batman: Knightfall Part 1: Knightfall,35.4988,9.095
1,False,980431,2026-07-24,Avatar Aang: The Last Airbender,59.0299,9.033
2,False,1007757,2026-05-01,Swapped,39.3270,8.800
3,False,1632181,2026-03-12,Accidental Partners,12.8826,8.800
4,False,1311031,2025-07-18,Demon Slayer: Kimetsu no Yaiba Infinity Castle,45.3120,8.801
5,False,1621552,2026-08-21,Facing El Chapo,31.3963,8.800
6,False,278,1994-09-23,The Shawshank Redemption,61.5979,8.734
7,False,238,1972-03-14,The Godfather,50.8297,8.700
8,False,687163,2026-03-15,Project Hail Mary,105.2510,8.633
9,False,1232449,2024-10-26,Young Hearts,13.8153,8.600
10,False,936075,2026-04-22,Michael,44.6957,8.596
11,False,389,1957-04-10,12 Angry Men,29.6109,8.576
12,False,240,1974-12-20,The Godfather Part II,32.0273,8.600
13,False,424,1993-12-15,Schindler's List,36.2427,8.570
14,False,1630423,2026-05-06,My Dearest Assassin,15.2472,8.560
15,False,1218925,2025-09-19,Chainsaw Man - The Movie: Reze Arc,28.9780,8.547
16,False,155,2008-07-16,The Dark Knight,57.8041,8.539
17,False,129,2001-07-20,Spirited Away,54.1760,8.537
18,False,497,1999-12-10,The Green Mile,33.2750,8.506
19,False,122,2003-12-17,The Lord of the Rings: The Return of the King,46.7927,8.506

In [15]:
for i in range(1,569):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=c697cd5701e7923cc1b74e9e45419362&'.format(i))
    temp_df=pd.DataFrame(response.json()['results']) [['adult','id','release_date','title','popularity','vote_average']]
    df=pd.concat([temp_df],ignore_index=True)

KeyError: 'results'

In [33]:
df

,adult,id,release_date,title,popularity,vote_average
0,False,1560520,2026-06-23,Batman: Knightfall Part 1: Knightfall,35.4988,9.095
1,False,980431,2026-07-24,Avatar Aang: The Last Airbender,59.0299,9.033
2,False,1007757,2026-05-01,Swapped,39.3270,8.800
3,False,1632181,2026-03-12,Accidental Partners,12.8826,8.800
4,False,1311031,2025-07-18,Demon Slayer: Kimetsu no Yaiba Infinity Castle,45.3120,8.801
5,False,1621552,2026-08-21,Facing El Chapo,31.3963,8.800
6,False,278,1994-09-23,The Shawshank Redemption,61.5979,8.734
7,False,238,1972-03-14,The Godfather,50.8297,8.700
8,False,687163,2026-03-15,Project Hail Mary,105.2510,8.633
9,False,1232449,2024-10-26,Young Hearts,13.8153,8.600
10,False,936075,2026-04-22,Michael,44.6957,8.596
11,False,389,1957-04-10,12 Angry Men,29.6109,8.576
12,False,240,1974-12-20,The Godfather Part II,32.0273,8.600
13,False,424,1993-12-15,Schindler's List,36.2427,8.570
14,False,1630423,2026-05-06,My Dearest Assassin,15.2472,8.560
15,False,1218925,2025-09-19,Chainsaw Man - The Movie: Reze Arc,28.9780,8.547
16,False,155,2008-07-16,The Dark Knight,57.8041,8.539
17,False,129,2001-07-20,Spirited Away,54.1760,8.537
18,False,497,1999-12-10,The Green Mile,33.2750,8.506
19,False,122,2003-12-17,The Lord of the Rings: The Return of the King,46.7927,8.506

In [34]:
df.shape

(20, 6)

In [37]:
df = pd.DataFrame()

for i in range(1, 569):

    params = {
        "api_key": "https://api.themoviedb.org/3/movie/top_rated?api_key=94ce7342958db89ec0cb3c63589e6255",
        "page": i
    }

    response = requests.get("https://api.themoviedb.org/3/movie/top_rated?api_key=94ce7342958db89ec0cb3c63589e6255", params=params)

    if response.status_code != 200:
        print("Error page:", i)
        print(response.json())
        break

    temp_df = pd.DataFrame(response.json()['results'])

    temp_df = temp_df[
        ['adult', 'id', 'release_date', 'title',
         'popularity', 'vote_average']
    ]

    df = pd.concat([df, temp_df], ignore_index=True)

print("Total rows:", len(df))

Error page: 501
{'success': False, 'status_code': 22, 'status_message': 'Invalid page: Pages start at 1 and max at 500. They are expected to be an integer.'}
Total rows: 10000

In [16]:
print(df.shape)

(20, 6)

In [17]:
df.to_csv("Movies.csv",index=False)